### ISSUE TITLE
Looking for manifest file

### ISSUE THREAD

**Issue by menjilx** [davestewart/great-suspender-recovery-tool#1]
It requires manifest file.
![image](https://user-images.githubusercontent.com/14908836/107074838-40310d80-6824-11eb-9478-734e0f12e790.png)

**Comment by davestewart** [comment]
You need to be in the `code/` folder :)

**Comment by menjilx** [comment]
> You need to be in the `code/` folder :)

Got it, thank you!

**Comment by davestewart** [comment]
Let me know how you get on! Would be interested to know how many tabs you recover as well?

**Comment by davestewart** [comment]
@menjilx it is now available in the [Chrome Web Store](https://chrome.google.com/webstore/detail/the-great-suspender-recov/ainlmpkfinfbbgdpimmldfdgpenmclmk)
