### ISSUE TITLE
Reverse sort order

### ISSUE THREAD

**Issue by lbogdan** [davestewart/great-suspender-recovery-tool#2]
First of all, very nice extension!

Right now the sort order is always ascending, but when sorting by "Date / Time", for example, it would be nice to be able to reverse the order so it's descending and you get the most recent suspended links first.

**Comment by davestewart** [comment]
Hey, Bogdan!

I guess I could add that pretty easy!

Let me look at it now...

**Comment by davestewart** [comment]
Pretty much there...

![image](https://user-images.githubusercontent.com/132681/107167092-d6de0580-69af-11eb-9b20-8cb7f2155e2f.png)

**Comment by davestewart** [comment]
OK, closed in 685867c4f1495efa30c251ef6944fbcaab37989d  📅 

![image](https://user-images.githubusercontent.com/132681/107169267-5f12d980-69b5-11eb-804f-c0c9569cd5d7.png)
